// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-eX-WTPcZYgrNU-t9t3T70NV7a9hHSg',
    appId: '1:695897120850:web:5ac145df3fa15cde5bff8b',
    messagingSenderId: '695897120850',
    projectId: 'blog-app-eae8a',
    authDomain: 'blog-app-eae8a.firebaseapp.com',
    storageBucket: 'blog-app-eae8a.appspot.com',
    measurementId: 'G-EQFDXTFD7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5LIOYx9JNrLnSrYpGIpjcCjpyNGlIptE',
    appId: '1:695897120850:android:64afffd85958a11e5bff8b',
    messagingSenderId: '695897120850',
    projectId: 'blog-app-eae8a',
    storageBucket: 'blog-app-eae8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSzSEs3hNEYcmO_vhfSnU0c7P_CKZ50M',
    appId: '1:695897120850:ios:14fe26de2257cac95bff8b',
    messagingSenderId: '695897120850',
    projectId: 'blog-app-eae8a',
    storageBucket: 'blog-app-eae8a.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSzSEs3hNEYcmO_vhfSnU0c7P_CKZ50M',
    appId: '1:695897120850:ios:611a0177e735710f5bff8b',
    messagingSenderId: '695897120850',
    projectId: 'blog-app-eae8a',
    storageBucket: 'blog-app-eae8a.appspot.com',
    iosBundleId: 'com.example.blogApp.RunnerTests',
  );
}
